### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by xaionaro** [Darwinnn/http-cache#2]
Hello.

1. I'd suggest to consider using of `fasthttp` to reduce HTTP-library overheads.

https://github.com/valyala/fasthttp

A related issue: https://github.com/julienschmidt/httprouter/issues/117

To make this project really useful you need to be faster than this:
http://antirez.com/blogdata/216/redisvsmemcached.png

2. Also, mutexes are slow. Especially on massively-concurrent cases (which a caching server is about). You may consider to use `atomicmap` instead (method `GetByBytes` to get a value) — it is oriented on a lot of reads (less writes and unsets [it's required to use `LockUnset()`, ATM :( ]).

https://github.com/xaionaro-go/atomicmap

https://github.com/Darwinnn/http-cache/blob/91198cf29953b44a1f0aacc76ca37d57a8daf3ef/cache.go#L36

Or, may be, it would be better to implement own mutexless thread-safe map.

3. You're coping data (and doing a memory allocation) here:

https://github.com/Darwinnn/http-cache/blob/91198cf29953b44a1f0aacc76ca37d57a8daf3ef/cache.go#L24

I'd suggest to use pointers, instead.

**Comment by Darwinnn** [comment]
Hello!
Well, first of all, I'd like to thank you for the feedback! I'll consider what you suggested here and come right to it.

**Comment by Darwinnn** [comment]
>1. Also, mutexes are slow. Especially on massively-concurrent cases (which is about a caching server of)

I've done some tests and it looks like atomic sync.Map is slower (about to 5k rps) than plain map with mutexes. At least on my 4cores i5 cpu. I'll be looking to test your lib and compare the results

**Comment by Darwinnn** [comment]
>1. I'd suggest to consider using of `fasthttp` to reduce HTTP-library overheads.

Wow, that actually doubled the RPS value.
